### ISSUE TITLE
відповідь на видалення

### ISSUE THREAD

**Issue by pecourses** [TarasOstasha/WebSocket#2]
https://github.com/TarasOstasha/WebSocket/blob/633e62c89b73e79b5d6fc0895f73beda17bfcf56/client/src/api/ws.js#L29
- в принципі, для видалення нам достатньо знати тільки id, тому можна передавати тільки його, щоб не ганяти зайві дані по мережі.

**Comment by TarasOstasha** [comment]
fixed
